"""empty message

Revision ID: 1dc3e64be083
Revises: 526946ce9a08
Create Date: 2020-05-30 00:22:57.563312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc3e64be083'
down_revision = '526946ce9a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'is_completed')
    # ### end Alembic commands ###
